services:
  app:
    image: mcp-python-interpreter
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    command: ["uv", "run", "server.py", "--transport", "sse", "--host", "0.0.0.0", "--port", "8050"]